### ISSUE TITLE
成功安装后，用的x-ui大概18个小时后，warp普通会自动断掉,导致无法使用。重启后解决。

### ISSUE THREAD

**Issue by Hikpy** [yonggekkk/warp-yg#10]
全部是跑的x-ui ,全部遇到同样的问题，是不是 会自动挂掉。
其他没安装warp-yg的则没有问题

**Comment by Hikpy** [comment]
而且warp的脚本  cf命令执行过长时间，每次查看状态 维护都及其不方便

**Comment by yonggekkk** [comment]
自动断开问题明天的新版本将修复！引入自动检测守护守

**Comment by yonggekkk** [comment]
> 而且warp的脚本 cf命令执行过长时间，每次查看状态 维护都及其不方便

由于检测的项目过多！看vps性能吧！这个没啥办法

**Comment by tianwen20** [comment]
> 

明天就出来了么，大佬

**Comment by Hikpy** [comment]
<img width="886" alt="image" src="https://user-images.githubusercontent.com/11391380/230347480-ad6c64a7-ac74-4363-93e1-55abf921e24c.png">
主要时间花在这个上面，打开这些url,这些URL地址都是超少，所以每次cf命令执行超过20分钟，不能一次先下载到本地吗？，否主要是 出了问题 ，x-ui完全不能用 超过半小时。

建议添加命令，cf 执行能第一时间 可以关掉 warp 保证 x-ui 随时可以啊

**Comment by Hikpy** [comment]
<img width="889" alt="image" src="https://user-images.githubusercontent.com/11391380/230348648-965d98cf-7ccf-4c72-a7ca-7e8d6863815f.png">
每次cf 都是执行这个，现在每次 都是超时，这些下能不能安装的时候 下载到本地。

**Comment by Hikpy** [comment]
现在问题是挂掉之后 ，vps就废掉了，出站IP没有用。x-ui无法正常工作。输入cf 命令就是  无休止的上面截图那样加载。长达半小时 还不行。  希望有个 命令 可以随时关掉。我就知道cf 这一个命令 。  大部分机器在重启之后 可以。有一台 重启后还不行。重点是脚本感觉不可控，出问题让停下来都不行。

**Comment by Hikpy** [comment]
希望尽快更新
1.脚本自动守护功能
2.添加命令一键关闭 warp或者脚本， 确保x-ui随时可以用
3.希望安装的时候需要的文件都全部下载下来，否则出问题去执行cf 完全没网，就是个死循环。


开个打赏页面，给支持一下勇哥

**Comment by N1body** [comment]
出现了同样的问题，重启后恢复

**Comment by tianwen20** [comment]
@yonggekkk 大佬今天什么时候更新呀

**Comment by yonggekkk** [comment]
已更新

**Comment by Hikpy** [comment]
@yonggekkk  能介绍一下 更新内容吗
warp 不可用的时候，能不能一键关闭，否则整个vps出站完全没网，整个vps都废了。客户端v2ray服务一直不可用的

**Comment by yonggekkk** [comment]
> @yonggekkk 能介绍一下 更新内容吗 warp 不可用的时候，能不能一键关闭，否则整个vps出站完全没网，整个vps都废了。客户端v2ray服务一直不可用的

systemctl stop wg-quick@wgcf
systemctl stop warp-go

**Comment by Hikpy** [comment]
感谢大佬提供命令，脚本
自动守护功能怎么启用呢，直接下载脚本重新执行cf  重新安装warp-go就好了吗

**Comment by yonggekkk** [comment]
> 感谢大佬提供命令，脚本 自动守护功能怎么启用呢，直接下载脚本重新执行cf 重新安装warp-go就好了吗

重装后自动启用

**Comment by Hikpy** [comment]
目前 还是几台机器 隔山差五 会断  需要人介入重启 ，其余机器没发现问题
