### ISSUE TITLE
选择团队一直都是账户升级失败

### ISSUE THREAD

**Issue by afycn** [yonggekkk/warp-yg#103]

**Comment by yonggekkk** [comment]
wgcf与warpgo 都试下

**Comment by afycn** [comment]
> wgcf与warpgo 都试下

都试了

**Comment by yonggekkk** [comment]
> > wgcf与warpgo 都试下
> 
> 都试了

去方案三，升级一个账户，把IPV6与私钥复制出来。。。用这种方式升级

**Comment by afycn** [comment]
> > > wgcf与warpgo 都试下
> 
> > 
> 
> > 都试了
> 
> 
> 
> 去方案三，升级一个账户，把IPV6与私钥复制出来。。。选择用IPV6与私钥这种方式升级

![image](https://github.com/yonggekkk/warp-yg/assets/43784195/0cf2619a-37eb-4fbf-936c-c4b0301c020e)

**Comment by yonggekkk** [comment]
> > > > wgcf与warpgo 都试下
> > 
> > 
> > > 
> > 
> > 
> > > 都试了
> > 
> > 
> > 去方案三，升级一个账户，把IPV6与私钥复制出来。。。选择用IPV6与私钥这种方式升级
> 
> ![image](https://private-user-images.githubusercontent.com/43784195/316228492-0cf2619a-37eb-4fbf-936c-c4b0301c020e.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExODU1NDAsIm5iZiI6MTcxMTE4NTI0MCwicGF0aCI6Ii80Mzc4NDE5NS8zMTYyMjg0OTItMGNmMjYxOWEtMzdlYi00ZmJmLTkzNmMtYzRiMDMwMWMwMjBlLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyM1QwOTE0MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MjYzNTA0MjM4NzdiZDBkMGNlZGEzMTAzMjI1YmQ1Nzk4ZGNhODA1NTc2YWM2NmU0Y2U3NDQyMjZiNmEwZTgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.P3urRXtoXbnAP6bDqovDmPQD4myJVyPZc742ACkdspY)



> > > > wgcf与warpgo 都试下
> > 
> > 
> > > 
> > 
> > 
> > > 都试了
> > 
> > 
> > 去方案三，升级一个账户，把IPV6与私钥复制出来。。。选择用IPV6与私钥这种方式升级
> 
> ![image](https://private-user-images.githubusercontent.com/43784195/316228492-0cf2619a-37eb-4fbf-936c-c4b0301c020e.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExODU1NDAsIm5iZiI6MTcxMTE4NTI0MCwicGF0aCI6Ii80Mzc4NDE5NS8zMTYyMjg0OTItMGNmMjYxOWEtMzdlYi00ZmJmLTkzNmMtYzRiMDMwMWMwMjBlLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyM1QwOTE0MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MjYzNTA0MjM4NzdiZDBkMGNlZGEzMTAzMjI1YmQ1Nzk4ZGNhODA1NTc2YWM2NmU0Y2U3NDQyMjZiNmEwZTgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.P3urRXtoXbnAP6bDqovDmPQD4myJVyPZc742ACkdspY)

你现在是输入所有gitlab的脚本都会这样报错吧？

**Comment by afycn** [comment]
> > > > > wgcf与warpgo 都试下
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 都试了
> 
> > > 
> 
> > > 
> 
> > > 去方案三，升级一个账户，把IPV6与私钥复制出来。。。选择用IPV6与私钥这种方式升级
> 
> > 
> 
> > ![image](https://private-user-images.githubusercontent.com/43784195/316228492-0cf2619a-37eb-4fbf-936c-c4b0301c020e.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExODU1NDAsIm5iZiI6MTcxMTE4NTI0MCwicGF0aCI6Ii80Mzc4NDE5NS8zMTYyMjg0OTItMGNmMjYxOWEtMzdlYi00ZmJmLTkzNmMtYzRiMDMwMWMwMjBlLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyM1QwOTE0MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MjYzNTA0MjM4NzdiZDBkMGNlZGEzMTAzMjI1YmQ1Nzk4ZGNhODA1NTc2YWM2NmU0Y2U3NDQyMjZiNmEwZTgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.P3urRXtoXbnAP6bDqovDmPQD4myJVyPZc742ACkdspY)
> 
> 
> 
> 
> 
> 
> 
> > > > > wgcf与warpgo 都试下
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 都试了
> 
> > > 
> 
> > > 
> 
> > > 去方案三，升级一个账户，把IPV6与私钥复制出来。。。选择用IPV6与私钥这种方式升级
> 
> > 
> 
> > ![image](https://private-user-images.githubusercontent.com/43784195/316228492-0cf2619a-37eb-4fbf-936c-c4b0301c020e.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExODU1NDAsIm5iZiI6MTcxMTE4NTI0MCwicGF0aCI6Ii80Mzc4NDE5NS8zMTYyMjg0OTItMGNmMjYxOWEtMzdlYi00ZmJmLTkzNmMtYzRiMDMwMWMwMjBlLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyM1QwOTE0MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MjYzNTA0MjM4NzdiZDBkMGNlZGEzMTAzMjI1YmQ1Nzk4ZGNhODA1NTc2YWM2NmU0Y2U3NDQyMjZiNmEwZTgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.P3urRXtoXbnAP6bDqovDmPQD4myJVyPZc742ACkdspY)
> 
> 
> 
> 你现在是输入所有gitlab的脚本都会这样报错吧？

不是的，普通账户可以开启成功，升级团队就不成功，获取私钥也没有

**Comment by yonggekkk** [comment]
你现在随便输入一个gitlab脚本，是不是也这样报错？

**Comment by afycn** [comment]
> 你现在随便输入一个gitlab脚本，是不是也这样报错？

sing-box也没有报错吖，我也安装了sing-box

**Comment by yonggekkk** [comment]
> > 你现在随便输入一个gitlab脚本，是不是也这样报错？
> 
> sing-box也没有报错吖，我也安装了sing-box

你卸载下WARP。重装下

**Comment by afycn** [comment]
> > > 你现在随便输入一个gitlab脚本，是不是也这样报错？
> 
> > 
> 
> > sing-box也没有报错吖，我也安装了sing-box
> 
> 
> 
> 你卸载下WARP。重装下

重装了，直接升级不行，私钥有了，但是没找到哪里用私钥升级😂

**Comment by yonggekkk** [comment]
> > > > 你现在随便输入一个gitlab脚本，是不是也这样报错？
> > 
> > 
> > > 
> > 
> > 
> > > sing-box也没有报错吖，我也安装了sing-box
> > 
> > 
> > 你卸载下WARP。重装下
> 
> 重装了，直接升级不行，私钥有了，但是没找到哪里用私钥升级😂

WGCF模式中的团队升级选项

**Comment by afycn** [comment]
> > > > > 你现在随便输入一个gitlab脚本，是不是也这样报错？
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > sing-box也没有报错吖，我也安装了sing-box
> 
> > > 
> 
> > > 
> 
> > > 你卸载下WARP。重装下
> 
> > 
> 
> > 重装了，直接升级不行，私钥有了，但是没找到哪里用私钥升级😂
> 
> 
> 
> WGCF模式中的团队升级选项

还是失败了

**Comment by yonggekkk** [comment]
换个VPS试试

**Comment by afycn** [comment]
> 换个VPS试试

一样的
