### ISSUE TITLE
loss 100%

### ISSUE THREAD

**Issue by pooriyara** [yonggekkk/warp-yg#11]
Hello. When I use "手动方式1：生成优选IP端口结果文件.bat", all ips give me 100% loss and none of them work. What could be the reason?

**Comment by yonggekkk** [comment]
> Hello. When I use "手动方式1：生成优选IP端口结果文件.bat", all ips give me 100% loss and none of them work. What could be the reason?

电脑上吗？那就没法了。。

**Comment by pooriyara** [comment]
> <img alt="@pooriyara" width="40" height="40" src="https://avatars.githubusercontent.com/u/128316895?s=80&amp;v=4">
Yes, I have tried it. After two weeks of trying, I was only able to receive 1 IP that had no 100% loss and worked for me, but even that IP is unstable and keeps disconnecting. This IP works with all ports. However, the problem is that besides this IP, no other IP works for me.all have loss 100%.
oh and i'm from Iran if it help.
It seems that some people here are experiencing the same problem as me, but others who are using the same ISP as me do not have this problem.

**Comment by pooriyara** [comment]
> > Hello. When I use "手动方式1：生成优选IP端口结果文件.bat", all ips give me 100% loss and none of them work. What could be the reason?
> 
> 电脑上吗？你试试手机在同样的网络测试下是不是同样的结果？

Yes, I have tried it. After two weeks of trying, I was only able to receive 1 IP that had no 100% loss and worked for me, but even that IP is unstable and keeps disconnecting. This IP works with all ports. However, the problem is that besides this IP, no other IP works for me.all have loss 100%.
oh and i'm from Iran if it help.
It seems that some people here are experiencing the same problem as me, but others who are using the same ISP as me do not have this problem.

**Comment by pooriyara** [comment]
Does anyone have a solution?
