### ISSUE TITLE
求一份源码

### ISSUE THREAD

**Issue by imabaymax** [yonggekkk/warp-yg#110]
iambaymax@qq.com
https://replit.com/@cjasq1/WARP-Wireguard-Register
我有点问题，账号是自动注册的是吧，可以脚本里设置账号么。另外生成的节点的流量可以查询么？

**Comment by yonggekkk** [comment]
目前忙，会慢慢开源的，相关教程都有说。WARP的账号最不值钱了，普通免费账号即可
