### ISSUE TITLE
一键生成2000多万GB流量的warp+密钥 不能使用

### ISSUE THREAD

**Issue by tangwwen** [yonggekkk/warp-yg#112]
1. 实时查看WARP在线监测情况（进入前请注意：退出且继续执行监测命令：ctrl+a+d，退出且关闭监测命令：ctrl+c ）
2. 重启WARP在线监测功能
3. 重置并自定义WARP在线监测时间间隔
4. 查看当天WARP在线监测日志
-----------------------------------------------
5. 更改Socks5+WARP端口
-----------------------------------------------
6. 用自备的warp密钥，慢慢刷warp+流量
7. 一键生成2000多万GB流量的warp+密钥
-----------------------------------------------
0. 退出
请选择：7
chmod: cannot access 'warpplus.sh': No such file or directory
timeout: failed to run command ‘./warpplus.sh’: No such file or directory
当前脚本累计已生成的warp+密钥已放置在/root/WARP+Keys.txt文件内
每重新执行一次的新密钥将放置在文件末尾（包括方案一与方案二）
cat: /root/WARP+Keys.txt: No such file or directory

**Comment by yonggekkk** [comment]
我这里测试没问题，可能VPS当前IP下载失败，多试试几次。。
下回开源后会迁移到github，应该就不会出问题了。

**Comment by maryjeck** [comment]
一样不行哦
