### ISSUE TITLE
No package cron available.

### ISSUE THREAD

**Issue by palislau** [yonggekkk/warp-yg#113]
请输入数字【0-3】:2
Loaded plugins: langpacks, ulninfo
No package cron available.
Error: Nothing to do

无法继续下去，这是为啥.

**Comment by yonggekkk** [comment]
是用centos7吗？换个系统吧

**Comment by palislau** [comment]
是这个：
[root@instance-20220116-1208 ~]# cat /etc/*-release
Oracle Linux Server release 7.9
NAME="Oracle Linux Server"
VERSION="7.9"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME="Oracle Linux Server 7.9"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:7:9:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://github.com/oracle/oracle-linux"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7"
ORACLE_BUGZILLA_PRODUCT_VERSION=7.9
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=7.9
Red Hat Enterprise Linux Server release 7.9 (Maipo)
Oracle Linux Server release 7.9

**Comment by yonggekkk** [comment]
换ubuntu 22.04
