### ISSUE TITLE
ss可以解锁，ssr无法解锁

### ISSUE THREAD

**Issue by shanghai20068** [yonggekkk/warp-yg#116]
谢谢作者的脚本，很方便。

服务器ssr和ss都搭建了，都能正常访问youtube，但ssr始终无法打开奈飞，ss就可以。试了很多次都是这样。

想请教一下这是为什么呢？按理说服务器的出站流量都被接管了。

**Comment by yonggekkk** [comment]
ssr就算了吧。。非主流了
