### ISSUE TITLE
登录chatgpt时出现了ERROR429

### ISSUE THREAD

**Issue by 738NGX** [yonggekkk/warp-yg#12]
登录chatgpt时出现了ERROR429
429
You are being rate limited.
We have detected an increased number of requests and have limited traffic temporarily.

If you think this is an error, please contact the systems administrator.

Your IP Address
104.28.211.105
Request ID
7b4855de9a258a48

**Comment by yonggekkk** [comment]
使用warp的IPV6吧，IPV4就那几个，已经用滥了。。

**Comment by 738NGX** [comment]
现在倒是登陆上去了，但是一直卡加载，问问题也加载不出来
![QQ截图20230408153619](https://user-images.githubusercontent.com/79038651/230709654-0a03a1a5-a164-459d-8c3a-7c4262840ef6.png)
VPS现在设置成这样
![QQ截图20230408153809](https://user-images.githubusercontent.com/79038651/230709727-5674521a-2d82-4aae-9250-b1aa104f6a04.png)

**Comment by yonggekkk** [comment]
用无痕模式，或者换个VPS的国家试试

**Comment by 738NGX** [comment]
重新开了个美国的VPS，开了无痕也还是老样子

**Comment by yonggekkk** [comment]
> 重新开了个美国的VPS，开了无痕也还是老样子

美国，日本，韩国，新加破别开了，开冷门区的国家

**Comment by 738NGX** [comment]
很神奇，一开始的日本VPS又好了，估计是之前暂时性抽风了
