### ISSUE TITLE
使用了后会导致，浏览器匿名模式下谷歌无法正常搜索，显示流量异常

### ISSUE THREAD

**Issue by milozen** [yonggekkk/warp-yg#121]
使用了后会导致，浏览器匿名模式下谷歌无法正常搜索，显示流量异常
原因在于将 google 的流量都导入了到了 warp中。
如何自定义哪些ip或者流量走warp，当前是吧谷歌流量都走了warp，我不想谷歌的流量走warp，应该如何修改。
其他的脚本是修改 ipset，但勇哥的脚本没找到修改的说明。
![image](https://github.com/user-attachments/assets/56eebde5-50d7-4a14-b760-e1e0826c180d)

**Comment by yonggekkk** [comment]
是的，脚本只有全局
