### ISSUE TITLE
用了之后ip 丢失，没法ping  也没法系统更新

### ISSUE THREAD

**Issue by wg-cn** [yonggekkk/warp-yg#125]
用了之后VPS网络崩了
ping: baidu.com: Temporary failure in name resolution

Kill进程也无法恢复

**Comment by yonggekkk** [comment]
1、终止warp-go： kill -15 $(pgrep warp-go)

2、终止wgcf： systemctl stop wg-quick@wgcf

**Comment by wg-cn** [comment]
> 1、终止warp-go： kill -15 $(pgrep warp-go)
> 
> 2、终止wgcf： systemctl stop wg-quick@wgcf
> 
> 输入脚本卸载


-----------------------------------------------------------------------
 IPV4地址：不存在IPV4地址
-----------------------------------------------------------------------
 IPV6地址：不存在IPV6地址
-----------------------------------------------------------------------

以上结果仅检测本地IP解锁情况，无法检测WARP出站分流的解锁情况

**重新输入脚本后 无反应**

**Comment by yonggekkk** [comment]
输入以上两个命令，再输入脚本

**Comment by wg-cn** [comment]
> 输入以上两个命令，再输入脚本

vps兼容有点问题，现在重启解决了 已经关闭了warp-go  谢谢
