### ISSUE TITLE
port closed error

### ISSUE THREAD

**Issue by arian2240** [yonggekkk/warp-yg#127]
Hi; thanks for fascinating script. Recently, I've faced an error that say warp-socks5 proxy is installed, but the port is closed. After that, I checked my server's firewall and it was disabled. 

VPS系统信息如下：
 操作系统: Ubuntu 20.04.6 LTS  内核版本: 6.11.2  CPU架构 : amd64v4  虚拟化类型: kvm
------------------------------------------------------------------------------------
 方案一：当前 IPV4 接管VPS出站情况如下（WARP监测关闭中）
 WARP状态：关闭中
 服务商 Hetzner 获取IPV4地址：ipv4  德国
 奈飞NF解锁情况：遗憾，当前IP仅解锁Netflix自制剧
 ChatGPT解锁情况：恭喜，当前IP完整解锁ChatGPT (网页+客户端)
------------------------------------------------------------------------------------
 方案一：当前 IPV6 接管VPS出站情况如下（WARP监测关闭中）
 WARP状态：关闭中
 服务商 Hetzner Online GmbH 获取IPV6地址：ipv6  德国
 奈飞NF解锁情况：遗憾，当前IP仅解锁Netflix自制剧
 ChatGPT解锁情况：恭喜，当前IP完整解锁ChatGPT (网页+客户端)
------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------
 方案二：当前 Socks5-WARP 官方客户端本地代理情况如下
 Socks5 WARP状态：已安装Socks5-WARP客户端，但端口处于关闭状态

**Comment by yonggekkk** [comment]
试试更换下最新系统

**Comment by arian2240** [comment]
> 试试更换下最新系统

you mean ubuntu 24?

**Comment by yonggekkk** [comment]
ubuntu 22.04

**Comment by arian2240** [comment]
> ubuntu 22.04

there is no choice for ubuntu 20.04 lts?
