### ISSUE TITLE
千万别安装这个， VPS G了

### ISSUE THREAD

**Issue by minLaoGe** [yonggekkk/warp-yg#13]
安装之后，连wrap的进程都杀不了， cf快捷键也进不去管理界面。后台的进程都不知道怎么杀，气死我了

**Comment by yonggekkk** [comment]
强制终止warp-go：kill -15 $(pgrep warp-go) 
终止wgcf：systemctl stop wg-quick@wgcf

**Comment by minLaoGe** [comment]
对不起是我太菜了，阿西吧
