### ISSUE TITLE
大佬 怎么配合v2ray?

### ISSUE THREAD

**Issue by zdoek001** [yonggekkk/warp-yg#132]
用了你的x-ui结合这个，先部署了x-ui，然后方案1上warp。但是x-ui的面板IP还是原来的，但是本地IPV4地址已经显示成warp的了。反而用warp IP访问不了，用原VPS IP反而可以

**Comment by yonggekkk** [comment]
warp的ip只能看！没实际用处

**Comment by yonggekkk** [comment]
> > warp的ip只能看！没实际用处
> 
> 我以为套warp可以隐藏原VPS IP的作用

被动隐藏
