### ISSUE TITLE
安裝WARP多功能VPS一键脚本成功，但無法訪問谷歌等網站

### ISSUE THREAD

**Issue by verzzz** [yonggekkk/warp-yg#14]
根據作者的一鍵安裝脚本，已經成功安裝
選擇了方案一：双栈IPV4+IPV6
和
方案二：安装Socks5-WARP
VPS搭建的是V2ray，電腦端已成功運行，可以正常訪問網絡，
但裝了作者的warp之後，谷歌、YouTube等不能正常訪問，只能訪問大陸網站。
只有在電腦端安裝wireguard，填寫方案三裏的配置信息才可以訪問。

另外，雖然成功配置了方案一、方案二，
但還是被chatgpt識別出來
VPS是vultr的，IP選擇了美國、波蘭，都是一樣的問題。

1.請問如何解決安裝warp后無法通過V2ray訪問互聯網； 不使用wireguard客戶端的話，是不是還得修改什麽配置？
2.成功配置了，但還是被chatgpt識別出來，是VPS服務商的問題還是IP的問題。

希望作者能抽空回答我的提問，謝謝。
以下是波蘭IP安裝脚本后的信息：

> VPS系统信息如下：
 VPS操作系统: Debian GNU/Linux 11 (bullseye)  内核版本: 5.10.0  CPU架构 : amd64  虚拟化类型: microsoft
------------------------------------------------------------------------------------
 方案一：当前 IPV4 接管出站流量情况如下（WARP监测已开启）
 WARP状态：运行中，WARP普通账户(无限WARP流量)
 服务商 Cloudflare 获取IPV4地址：104.28.217.42  美国
 奈飞NF解锁情况：遗憾，当前IP仅可观看Netflix自制剧
 ChatGPT解锁情况：恭喜，当前IP支持访问ChatGPT官网服务
------------------------------------------------------------------------------------
 方案一：当前 IPV6 接管出站流量情况如下（WARP监测已开启）
 WARP状态：运行中，WARP普通账户(无限WARP流量)
 服务商 Cloudflare 获取IPV6地址：2a09:bac5:80c9:2dc::49:1ae  美国
 奈飞NF解锁情况：恭喜，当前IP支持观看Netflix非自制剧
 ChatGPT解锁情况：恭喜，当前IP支持访问ChatGPT官网服务
------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------
 方案二：当前Socks5-WARP官方客户端本地代理情况如下
 Socks5 WARP状态：运行中，WARP普通账户(无限WARP流量)
 Socks5 端口：40000
 服务商 Cloudflare 获取IPV4地址：104.28.193.182  美国
 奈飞NF解锁情况：恭喜，当前IP支持观看Netflix非自制剧
 ChatGPT解锁情况：恭喜，当前IP支持访问ChatGPT官网服务

**Comment by yonggekkk** [comment]
用什么代理？确保测试代理的ip结果为以上的warp的ip！看下warp系列后几期教程

**Comment by yonggekkk** [comment]
> > 
> 
> 我用的是233boy的一鍵安裝脚本，傳輸協議是默認的kcp

换别的

**Comment by verzzz** [comment]
> > > 
> > 
> > 
> > 我用的是233boy的一鍵安裝脚本，傳輸協議是默認的kcp
> 
> 换别的
感謝！！！我重建了一個VPS
用你的那個x-ui項目搭建了v2ray
然後再用這個項目的一鍵安裝脚本
安裝了IPV6單棧，可以成功瞞過chatGPT了
可惜的是現在Chat GPT限制普通用戶登錄了，不過Bing可以正常訪問了。再次感謝！！
PS：目前只安裝了方案一的單棧IPV6，雙棧安裝或單棧IPV4時縂是在獲取賬號。。。

**Comment by billy0ma** [comment]
<img width="730" alt="截屏2024-12-16 21 06 38" src="https://github.com/user-attachments/assets/94650591-e3fe-493c-8146-eaaffd3a61ee" />

请问甬哥，如图，我始终无法安装“方案二：安装Socks5-WARP"，只要选择2就自动退出脚本了
这是什么原因，应该如何解决？

**Comment by yonggekkk** [comment]
> <img alt="截屏2024-12-16 21 06 38" width="730" src="https://private-user-images.githubusercontent.com/7895361/396106231-94650591-e3fe-493c-8146-eaaffd3a61ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzNTczODEsIm5iZiI6MTczNDM1NzA4MSwicGF0aCI6Ii83ODk1MzYxLzM5NjEwNjIzMS05NDY1MDU5MS1lM2ZlLTQ5M2MtODE0Ni1lYWFmZmQzYTYxZWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTZUMTM1MTIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzYwN2E5MjQwMzBiYzgyZDc2YjRiMGRhZmI5YTQ1OWJjYTM2NjVkYTI0ZDFlOTJmNWViMDE3NDk4OTg0NzdiYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.1v98rjtg0Tx0ogZMvUTM9-VZPkqv7NsoSSzJOTHTguc">
> 请问甬哥，如图，我始终无法安装“方案二：安装Socks5-WARP"，只要选择2就自动退出脚本了 这是什么原因，应该如何解决？

重启下VPS试试

**Comment by hsx2333** [comment]
> <img alt="截屏2024-12-16 21 06 38" width="730" src="https://private-user-images.githubusercontent.com/7895361/396106231-94650591-e3fe-493c-8146-eaaffd3a61ee.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjExMjUwOTgsIm5iZiI6MTc2MTEyNDc5OCwicGF0aCI6Ii83ODk1MzYxLzM5NjEwNjIzMS05NDY1MDU5MS1lM2ZlLTQ5M2MtODE0Ni1lYWFmZmQzYTYxZWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MTAyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTEwMjJUMDkxOTU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTM2MDcxYmQ5NTY2YjNmMGUxOGU4OTFmMjZmZGEwYTc0NGIxZGY2MmFiMzAzM2MwZmVhMDI1YzkzMzJmMGM0YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.4Kutv8HABu5ElHdj9oHmciubJ78g6M2K2LN6XbFdUjM">
> 请问甬哥，如图，我始终无法安装“方案二：安装Socks5-WARP”，只要选择2就自动退出脚本了 这是什么原因，应该如何解决？

如果是arm机器，我pr去掉了限制等甬哥确认，之前不支持arm机器安装socks5-WARP，会静默退出。
