### ISSUE TITLE
怎么配合v2ray呀

### ISSUE THREAD

**Issue by hyx52077** [yonggekkk/warp-yg#15]
安装好了 但不会用,我是安装国外服务器, 
我之前是用这个脚本 https://github.com/233boy/v2ray
还忘作者指教一下,我是重装系统装你这个脚本的.安装了不会用

**Comment by yonggekkk** [comment]
用ws或者tcp协议吧。安装方案一自动生效接管出站流量

**Comment by hhzrz** [comment]
如果v2ray（ws+tls）本身就是跑在docker里面的话，会提示方法一会导致docker失效。请问这怎么处理？

**Comment by yonggekkk** [comment]
> 如果v2ray（ws+tls）本身就是跑在docker里面的话，会提示方法一会导致docker失效。请问这怎么处理？

目前无解！原理冲突！除非docker改host模式

**Comment by hyx52077** [comment]
你的 x-ui仓库 跟 你这个仓库 ,配合解决了。
