### ISSUE TITLE
鸿蒙OS3.0上安装1.1.1.1 warp后，无法正常开启！

### ISSUE THREAD

**Issue by hanjiangke18** [yonggekkk/warp-yg#16]
手机上用鸿蒙OS3.0，安装1.1.1.1 warp客户端后，开启时出现“出现致命错误，cloudflare已停止1.1.1.1服务”；
另外，在VPS上用脚本，试验几次升级team团队版，都显示warp普通账户。

**Comment by yonggekkk** [comment]
必须先安装google play服务

**Comment by hanjiangke18** [comment]
google play服务是已经安装了的！还发现一个问题，开启1.1.1.1 warp软件时，如果选择仅DNS就可以进入，一切换到warp就会出现上述致命错误！

**Comment by yonggekkk** [comment]
> google play服务是已经安装了的！还发现一个问题，开启1.1.1.1 warp软件时，如果选择仅DNS就可以进入，一切换到warp就会出现上述致命错误！

去谷歌商店下载1.1.1.1

**Comment by hanjiangke18** [comment]
就是谷歌商店下载的1.1.1.1，换了apkpure下载，也是一样的问题！安装了N遍都不行。

**Comment by yonggekkk** [comment]
普通账户有设备id吗？估计没有………试下wg客户端！华为手机不了解

**Comment by hanjiangke18** [comment]
仅DNS模式登录，没有设备ID！wg客户端登录的是普通账户，能不能用来登录team账户呢？

**Comment by yonggekkk** [comment]
> 仅DNS模式登录，没有设备ID！wg客户端登录的是普通账户，能不能用来登录team账户呢？

看教程吧。

**Comment by Lockik** [comment]
我的华为手机也不行

**Comment by yonggekkk** [comment]
> 我的华为手机也不行

安装好谷歌服务，保证1.1.1.1是从这个谷歌商店下载下来的

**Comment by dfmjndm** [comment]
遇到了了一样的情况，Google框架都正常的，从商店安装的warp

**Comment by yonggekkk** [comment]
> 遇到了了一样的情况，Google框架都正常的，从商店安装的warp

确保有设备id

**Comment by mamamii** [comment]
> 手机上用鸿蒙OS3.0，安装1.1.1.1 warp客户端后，开启时出现“出现致命错误，cloudflare已停止1.1.1.1服务”； 另外，在VPS上用脚本，试验几次升级team团队版，都显示warp普通账户。

试了半天，跟你的问题一样，安装后没有key，添加密钥也不能保存。通过zero trust登录反复试验均失败告终

**Comment by shawzhio** [comment]
请问大神怎么解决，一样出现致命错误

**Comment by wpsdoo** [comment]
华为就是垃圾，荣耀手机也是垃圾。一样都不可以用。小米手机就正常。我的是不能打开google网站。直接显示404。YouTube正常。垃圾荣耀

**Comment by dfmjndm** [comment]
小米手机也是垃圾，以前开warp报致命错误

**Comment by baizhi2022** [comment]
warp 开不了谷歌商店，刷个视频还行，想开谷歌商店，GPT只能用Nekoray，这个非常好用。

**Comment by baizhi2022** [comment]
![prod-novel-20240518-3aaf943f-27e2-416c-8082-c6deee5e7369](https://github.com/yonggekkk/warp-yg/assets/107926749/2a1bdca4-23bb-457d-bcfc-c3c71badcf46)
可以交流

**Comment by buxiuzhixing** [comment]
一样用不了
