### ISSUE TITLE
warp-go 自动停止了

### ISSUE THREAD

**Issue by ZEERDEER** [yonggekkk/warp-yg#19]
一键安装warp-go后，开启了ipv4 没过多久warp就掉了。 Ubuntu 22 搬瓦工

**Comment by ZEERDEER** [comment]
> > 一键安装warp-go后，开启了ipv4 没过多久warp就掉了。 Ubuntu 22 搬瓦工
> 
> 恢复成原ip了吧？

是的是的，然后就要重新cf 然后重新开启。

**Comment by yonggekkk** [comment]
> > > 一键安装warp-go后，开启了ipv4 没过多久warp就掉了。 Ubuntu 22 搬瓦工
> > 
> > 
> > 恢复成原ip了吧？
> 
> 是的是的，然后就要重新cf 然后重新开启。

卸载warpgo，换成wgcf
