### ISSUE TITLE
warp-go 还是普遍会出现不稳定断掉的情况，有的是断掉恢复原来IP，有的需要重启 才能恢复上网，每天1-2次

### ISSUE THREAD

**Issue by Hikpy** [yonggekkk/warp-yg#20]

**Comment by yonggekkk** [comment]
能不用下你的vps？

**Comment by Hikpy** [comment]
> 能不用下你的vps？你tg是？

<img width="171" alt="image" src="https://user-images.githubusercontent.com/11391380/233158740-fd844ba4-6cb4-4a3a-8170-84e286393d8f.png">

**Comment by yonggekkk** [comment]
已加

**Comment by sonwa** [comment]
遇到同样问题。断掉ping可以ping得通，但连ssh都无法连接。要重新才恢复

**Comment by lp380490944** [comment]
同样情况，突然ip没了，变成vps原生ip了

**Comment by yonggekkk** [comment]
> 

什么vps

**Comment by yonggekkk** [comment]
> 同样情况，突然ip没了，变成vps原生ip了

试下wgcf

**Comment by sonwa** [comment]
同样问题，换了wgcf还是断线。  使用搬瓦工 centos7

**Comment by sonwa** [comment]
<img width="720" alt="image" src="https://user-images.githubusercontent.com/1425134/233592953-42ab2082-c9cd-4ee6-88d8-0491d6fec457.png">

**Comment by sonwa** [comment]
<img width="725" alt="image" src="https://user-images.githubusercontent.com/1425134/233594647-dc50145f-bb8b-4cff-bcf7-cbb7f94b0f16.png">
掉了，按1重新装才行

**Comment by yonggekkk** [comment]
> <img alt="image" width="725" src="https://user-images.githubusercontent.com/1425134/233594647-dc50145f-bb8b-4cff-bcf7-cbb7f94b0f16.png">
> 
> 掉了，按1重新装才行

换ub22.04戓deb11呢
