### ISSUE TITLE
服务器重启后，warp不会自动运行

### ISSUE THREAD

**Issue by itdsgithub** [yonggekkk/warp-yg#23]
就是服务器重启后，再输入"cf"查看这些配置信息，显示warp已关闭，按选项是没法开启的，只能手动再重新安装一遍，不知道其他人有没有这样的情况

**Comment by yonggekkk** [comment]
什么vps什么系统？用wgcf试试

**Comment by itdsgithub** [comment]
> 什么vps什么系统？用wgcf试试

我又试了一下，还是不行
 当前 CFwarp 脚本版本号：23.4.11 V 0.9.9  重置版第四版 ，已是最新版本

 当前 WARP-GO 已安装内核版本号：1.0.8 ，已是最新版本
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 VPS系统信息如下：
 VPS操作系统: Debian GNU/Linux 10 (buster)  内核版本: 6.2.7  CPU架构 : amd64v2  虚拟化类型: kvm
------------------------------------------------------------------------------------
 方案一：当前 IPV4 接管出站流量情况如下（WARP监测已开启）
 WARP+状态：运行中，WARP+Teams账户(无限WARP+流量)
 服务商 Cloudflare 获取IPV4地址：104.28.203.54  美国
 奈飞NF解锁情况：恭喜，当前IP支持观看Netflix非自制剧
 ChatGPT解锁情况：恭喜，当前IP支持访问ChatGPT官网服务
------------------------------------------------------------------------------------
 方案一：当前 IPV6 接管出站流量情况如下（WARP监测已开启）
 WARP+状态：运行中，WARP+Teams账户(无限WARP+流量)
 服务商 Cloudflare 获取IPV6地址：2a09:bac5:cad4:154b::21f:af  美国
 奈飞NF解锁情况：恭喜，当前IP支持观看Netflix非自制剧
 ChatGPT解锁情况：恭喜，当前IP支持访问ChatGPT官网服务
————————
但是，重启服务器后，输入cf，看到的信息是：
warp+状态：已关闭，
我试过选项里重新开启，总是失败，只能重新安装一遍才行。

**Comment by yonggekkk** [comment]
> > 什么vps什么系统？用wgcf试试
> 
> 我又试了一下，还是不行 当前 CFwarp 脚本版本号：23.4.11 V 0.9.9 重置版第四版 ，已是最新版本
> 
> 当前 WARP-GO 已安装内核版本号：1.0.8 ，已是最新版本
> 
> ```
>  VPS系统信息如下：
>  VPS操作系统: Debian GNU/Linux 10 (buster)  内核版本: 6.2.7  CPU架构 : amd64v2  虚拟化类型: kvm
> ------------------------------------------------------------------------------------
>  方案一：当前 IPV4 接管出站流量情况如下（WARP监测已开启）
>  WARP+状态：运行中，WARP+Teams账户(无限WARP+流量)
>  服务商 Cloudflare 获取IPV4地址：104.28.203.54  美国
>  奈飞NF解锁情况：恭喜，当前IP支持观看Netflix非自制剧
>  ChatGPT解锁情况：恭喜，当前IP支持访问ChatGPT官网服务
> ------------------------------------------------------------------------------------
>  方案一：当前 IPV6 接管出站流量情况如下（WARP监测已开启）
>  WARP+状态：运行中，WARP+Teams账户(无限WARP+流量)
>  服务商 Cloudflare 获取IPV6地址：2a09:bac5:cad4:154b::21f:af  美国
>  奈飞NF解锁情况：恭喜，当前IP支持观看Netflix非自制剧
>  ChatGPT解锁情况：恭喜，当前IP支持访问ChatGPT官网服务
> ————————
> 但是，重启服务器后，输入cf，看到的信息是：
> warp+状态：已关闭，
> 我试过选项里重新开启，总是失败，只能重新安装一遍才行。
> ```

哪家vps？

**Comment by jacobswin** [comment]
我的搬瓦工重启后也没自动启动

**Comment by yonggekkk** [comment]
> 我的搬瓦工重启后也没自动启动

换系统看看。。
