### ISSUE TITLE
ipv6问题

### ISSUE THREAD

**Issue by sonwa** [yonggekkk/warp-yg#25]
ipv4经常访问不到ChatGPT，现在直接只装“安装WARP单栈IPV6”，访问ChatGPT怎样强制通过ipv6访问？

**Comment by yonggekkk** [comment]
参考https://youtu.be/8N1rSoAMil0
教程中一个失误就是设置方法了。

**Comment by sonwa** [comment]
不错👍。按视频装了x-ui可以用到v6了。不过不是用x2ray，用的是shadowsocks连接。我用的是macOS系统，用x2ray一直连接失败。换了shadowsocks协议一连就行了，就出了v6IP。shadowsocks就设一下端口，加密方式，密码，其它啥都不用设了。
