### ISSUE TITLE
速度慢

### ISSUE THREAD

**Issue by FlandreScarle7** [yonggekkk/warp-yg#27]
直接在自己电脑上开启warp+ speedteat延迟300多但是网速可以跑到480mbps
在服务器上开warp-go 服务器上speedtest延迟5ms内 但是网速被锁定在85mbps左右 电脑上使用服务器的代理也是85mbps左右
这是怎么回事呢 被限速了吗 服务器是美西的 服务器不开warp上下速度都可达2000mbps

**Comment by yonggekkk** [comment]
试下wgcf
