### ISSUE TITLE
新人求助，装完之后脚本显示已支持openai但还是连不上，再cf进脚本发现warp又关了。查IP地址也是VPS的IP

### ISSUE THREAD

**Issue by rrfopai** [yonggekkk/warp-yg#29]
每次装完warp，就被关闭，打开也没用，IP地址查询都是VPS的。
新人按照甬哥的视频安装的，VPS试过vultr和谷歌云，为何warp在vps上都不能成功开启，感谢解答！
![image](https://user-images.githubusercontent.com/131804114/235315370-76dc85fc-f497-457e-b397-ac45cba941a1.png)
![image](https://user-images.githubusercontent.com/131804114/235315514-cabe6e77-f9d0-45e4-836b-14bcdb8d7635.png)

**Comment by yonggekkk** [comment]
干净环境下重新安装下wgcf试试
