### ISSUE TITLE
不知道是我的问题还是bug了

### ISSUE THREAD

**Issue by seagullz4** [yonggekkk/warp-yg#30]
刚开是装了ipv4/6的双闸，一切正常使用，使用你的那个x-ui进行分流也是正常使用的，后来我就不想使用双闸了，单闸ipv6就行，我的ipv4就不想被warp代理，于是就点那个卸载warp选项，卸载也是非常成功，然后我就安装warp选ipv6，也是成功了![Screenshot_2023-04-30-07-18-50-184_com.server.auditor.ssh.client.jpg](https://user-images.githubusercontent.com/96653729/235328215-d47dee45-bbc5-4984-afb3-b12fc3017707.jpg)

ipv4是我自己的，然后我就想着用x-ui分流，结果全部失败，全部将出站流量定向到我的原生ipv4，改全局ipv6也没有用，重启面板也试过。

求甬哥侃侃侃

**Comment by yonggekkk** [comment]
你现在是warp v4+v6，无法原生v4

**Comment by seagullz4** [comment]
这个是我后面又改了，但是我重启了一下系统，结果就成了，麻烦你了哈，甬哥，快去吃早饭吧
