### ISSUE TITLE
监测时间段希望能够自定义，时间适当长一点

### ISSUE THREAD

**Issue by Hikpy** [yonggekkk/warp-yg#38]
60秒的话，有点短，服务器会频繁出现断网，x-ui表现为一直断。
保证网络可用是第一位的。

**Comment by Hikpy** [comment]
希望能保证 网络可用 。网络不可用的时间尽可能少。

**Comment by yonggekkk** [comment]
> 希望能保证 网络可用 。网络不可用的时间尽可能少。

OK。几天后会更新加入
