### ISSUE TITLE
Warp go is disable after a while

### ISSUE THREAD

**Issue by techjoyment** [yonggekkk/warp-yg#41]
Hi
I installed Warp-go successfully on an OpenVZ VPS. After hours it becomes disable and I must restart the service to work again.

**Comment by yonggekkk** [comment]
> 
What is the ip address when disable

**Comment by techjoyment** [comment]
> > 
> 
> What is the ip address when disable

It's back to my original VPS IP and Warp became inactive (dead). I tried wgcf but it doesn't install at all.

**Comment by yonggekkk** [comment]
> 

When restoring to original ip, you can wait 10 minutes to see if it restores to warp ip!!! The script has added automatic recovery! You can see the youtube description
