### ISSUE TITLE
vpn profiles keep disconnecting after using warp on server

### ISSUE THREAD

**Issue by NativitY996** [yonggekkk/warp-yg#42]
hello,
Thanks for your efforts

I have a problem; in you're **booth method** (WGCF or WARP-GO) after setup warp on vpn server, **vpn profiles keep disconnecting** for a while (like 2 min) and after that, they connect again! I don't know where the problem is!! but i try install warp again and it's do nothing.

I use 3x-ui (1.8.1 xray ver) panel and vless+tcp+tls , trojan+tcp+tls protocols
I would be grateful if you could help me solve this problem.

**Comment by yonggekkk** [comment]
3xui can not run？

**Comment by yonggekkk** [comment]
It will be back to normal after a while, right?

**Comment by yonggekkk** [comment]
You can try to change another client
