### ISSUE TITLE
wgcf 和 warp-go 均因获取warp IP失败无法安装

### ISSUE THREAD

**Issue by o-ov** [yonggekkk/warp-yg#44]
bwg vps，系统是centos9，之前脚本没有问题，已经正常使用了几个月。昨天重置了系统，重新安装cfwarp，出现两种方式均因获取warp IP失败无法完成warp安装。多次尝试，并切换了服务器区域到NY也不行。

**Comment by yonggekkk** [comment]
都是运行10次失败吗？还有有报错提示？

**Comment by o-ov** [comment]
都是10次失败，没有报错提示

**Comment by o-ov** [comment]
<img width="782" alt="image" src="https://github.com/yonggekkk/warp-yg/assets/20625652/b21bdffd-b438-472d-abcc-5e15c979b33c">

**Comment by yonggekkk** [comment]
> <img alt="image" width="782" src="https://user-images.githubusercontent.com/20625652/245677528-b21bdffd-b438-472d-abcc-5e15c979b33c.png">

什么VPS？进群叫我下

**Comment by o-ov** [comment]
搬瓦工

**Comment by o-ov** [comment]
> > <img alt="image" width="782" src="https://user-images.githubusercontent.com/20625652/245677528-b21bdffd-b438-472d-abcc-5e15c979b33c.png">
> 
> 什么VPS？进群叫我下

进啥群？

**Comment by yonggekkk** [comment]
> > > <img alt="image" width="782" src="https://user-images.githubusercontent.com/20625652/245677528-b21bdffd-b438-472d-abcc-5e15c979b33c.png">
> > 
> > 
> > 什么VPS？进群叫我下
> 
> 进啥群？

TG群呀

**Comment by o-ov** [comment]
切换了centos 到ubantu 瞬间解决，估计是centos各种不更新支持导致的

**Comment by yonggekkk** [comment]
> 切换了centos 到ubantu 瞬间解决，估计是centos各种不更新支持导致的

新手都建议ub或者deb的
