### ISSUE TITLE
Problem with docker

### ISSUE THREAD

**Issue by mmdjvdad** [yonggekkk/warp-yg#45]
I am experiencing issues accessing Docker containers on my VPS after activating Cloudflare Warp, it's possible that the Warp VPN is affecting the network routing and causing the containers to become inaccessible from outside the VPS. Any thing I can do to fix this? Is there any way to have both of them, working fine?

**Comment by mmdjvdad** [comment]
can this project run in a docker container then, navigate the containers network through warp?

**Comment by yonggekkk** [comment]
You can change docker to host mode
