### ISSUE TITLE
Problem with floating ip

### ISSUE THREAD

**Issue by ali4hk** [yonggekkk/warp-yg#46]
when floating ip add and turn on warp make problem to connection the ip.
what should do after addding floating

**Comment by yonggekkk** [comment]
Please upload a picture

**Comment by ali4hk** [comment]
i found that when we turn off the vps and add a ip to the vps 
or add floating ip to the vps 
or change the ipv4 of the vps 
the new added ip can not connect to the vps
also with restarting the cfwarp with this command cf - 5 - 2 or cf - 5- 1 cf - 5 -2
what should do after changing ip to make effect the warp ?

**Comment by ali4hk** [comment]
我发现当我们关闭 vps 并向 vps 添加 ip 时
或者给vps添加浮动ip
或者更改vps的ipv4
新添加的ip连不上vps
还可以使用此命令 cf - 5 - 2 或 cf - 5- 1 cf - 5 -2 重新启动 cfwarp
更改 ip 后应该做什么才能使 warp 生效？

**Comment by yonggekkk** [comment]
没生效？vps的问题
