### ISSUE TITLE
Warp IP acquisition failed!

### ISSUE THREAD

**Issue by sinazlf** [yonggekkk/warp-yg#47]
共执行10次，第1次获取warp的IP中……
遗憾！warp的IP获取失败
共执行10次，第2次获取warp的IP中……
遗憾！warp的IP获取失败
共执行10次，第3次获取warp的IP中……
遗憾！warp的IP获取失败
共执行10次，第4次获取warp的IP中……
遗憾！warp的IP获取失败
共执行10次，第5次获取warp的IP中……
遗憾！warp的IP获取失败
共执行10次，第6次获取warp的IP中……
遗憾！warp的IP获取失败
共执行10次，第7次获取warp的IP中……
遗憾！warp的IP获取失败
共执行10次，第8次获取warp的IP中……
遗憾！warp的IP获取失败
共执行10次，第9次获取warp的IP中……
遗憾！warp的IP获取失败
共执行10次，第10次获取warp的IP中……
遗憾！warp的IP获取失败
安装WARP失败，还原VPS，卸载Wgcf-WARP组件中……

please help

**Comment by yonggekkk** [comment]
You can try Wgcf or warp-go

**Comment by sinazlf** [comment]
It did not activate, still the same problem
