### ISSUE TITLE
账户

### ISSUE THREAD

**Issue by wnbh** [yonggekkk/warp-yg#5]
切换账户一直失败

**Comment by yonggekkk** [comment]
> 切换账户一直失败

发图看看

**Comment by wnbh** [comment]
> > 切换账户一直失败
> 
> 发图看看

![Screenshot_20230319_180006](https://user-images.githubusercontent.com/30308165/226168021-83cad230-76e2-4aee-a096-85f152df8dc2.jpg)
使用warp-go命令切换账户成功了 但是使用warp-go生成wireguard配置连接不上 接着使用你的脚本生成配置就能连上 发现问题出在Endpoint = 162.159.193.10:1701 只有这个地址能连接成功还是可以自选？自选ip段是什么？望大佬解答

**Comment by yonggekkk** [comment]
> > > 切换账户一直失败
> > 
> > 
> > 发图看看
> 
> ![Screenshot_20230319_180006](https://user-images.githubusercontent.com/30308165/226168021-83cad230-76e2-4aee-a096-85f152df8dc2.jpg) 使用warp-go命令切换账户成功了 但是使用warp-go生成wireguard配置连接不上 接着使用你的脚本生成配置就能连上 发现问题出在Endpoint = 162.159.193.10:1701 只有这个地址能连接成功还是可以自选？自选ip段是什么？望大佬解答

什么vps？systemd都没

**Comment by wnbh** [comment]
> > > > 切换账户一直失败
> > > 
> > > 
> > > 发图看看
> > 
> > 
> > ![Screenshot_20230319_180006](https://user-images.githubusercontent.com/30308165/226168021-83cad230-76e2-4aee-a096-85f152df8dc2.jpg) 使用warp-go命令切换账户成功了 但是使用warp-go生成wireguard配置连接不上 接着使用你的脚本生成配置就能连上 发现问题出在Endpoint = 162.159.193.10:1701 只有这个地址能连接成功还是可以自选？自选ip段是什么？望大佬解答
> 
> 什么vps？systemd都没

安卓termux

**Comment by yonggekkk** [comment]
> 

装不上的

**Comment by yonggekkk** [comment]
> 

关于warp自选…下期视频教程会详解

**Comment by wnbh** [comment]
> > 
> 
> 关于warp自选…下期视频教程会详解

好的
