### ISSUE TITLE
unsuccessfully obtained warp ip after 10 effort

### ISSUE THREAD

**Issue by rahavard01** [yonggekkk/warp-yg#51]
i will try warp go & wgcf for obtained warp ip, but not success evereytime
pls help

**Comment by rahavard01** [comment]
my vps is from contabo

**Comment by yonggekkk** [comment]
Change to another VPS or region

**Comment by sinazlf** [comment]
منم همین مشکلو داشتم،دیتاسنترو تغییر بده!
