### ISSUE TITLE
Very High server RAM Usage!

### ISSUE THREAD

**Issue by NativitY996** [yonggekkk/warp-yg#54]
hi,

as you see in pic, after im using of warp proxy in my server, ram usage going to max sometime and my proxys be timeout!
pls fix this problem

![Screenshot 2023-06-30 123524](https://github.com/yonggekkk/warp-yg/assets/126234163/15ab948a-6589-4e30-98aa-bc8c66fe4815)

**Comment by yonggekkk** [comment]
warp-cli has such a problem, it can only be restarted

**Comment by yonggekkk** [comment]
you can try it
