### ISSUE TITLE
自动设置获取到的第一个IP

### ISSUE THREAD

**Issue by XiongDemo** [yonggekkk/warp-yg#55]
```
@echo off & setlocal enabledelayedexpansion
set lineFlag=0
for /f "delims=*," %%i in (result.csv) do (
set /a lineFlag+=1
  if !lineFlag!==2 (
    set endpoint=%%i
	warp-cli.exe clear-custom-endpoint
	warp-cli.exe set-custom-endpoint !endpoint!
	echo 当前端点已经设置为 !endpoint!
  )
)
pause
```

在 WIN端warp自选IP(手动+自动) 目录下新建  3.bat   将以上代码放进去 就能自动设置啦

**Comment by yonggekkk** [comment]
?

**Comment by yonggekkk** [comment]
> ```
> @echo off & setlocal enabledelayedexpansion
> set lineFlag=0
> for /f "delims=*," %%i in (result.csv) do (
> set /a lineFlag+=1
>   if !lineFlag!==2 (
>     set endpoint=%%i
> 	warp-cli.exe clear-custom-endpoint
> 	warp-cli.exe set-custom-endpoint !endpoint!
> 	echo 当前端点已经设置为 !endpoint!
>   )
> )
> pause
> ```
> 
> 在 WIN端warp自选IP(手动+自动) 目录下新建 3.bat 将以上代码放进去 就能自动设置啦

自动设置有了呀

**Comment by yonggekkk** [comment]
> 我的电脑 运行不了VBS 我就自己写了一个
> 
> Zero Trust 是无限流量吗？

是无限
