### ISSUE TITLE
socks5 warp not available now

### ISSUE THREAD

**Issue by l3lack-eyes** [yonggekkk/warp-yg#60]
socks5 warp not available now
 方案二：当前 Socks5-WARP 官方客户端本地代理情况如下
 Socks5 WARP状态：未安装Socks5-WARP客户端

**Comment by yonggekkk** [comment]
选择2，进行安装？失败了？发下报错信息

**Comment by l3lack-eyes** [comment]
there's no error message when I choose 2 it does nothing  
![Screenshot 2023-07-24 171729](https://github.com/yonggekkk/warp-yg/assets/138435463/c97307f1-c196-4704-b572-d4a8eb76836f)

**Comment by yonggekkk** [comment]
reboot vps
