### ISSUE TITLE
Error: Operation not authorized in this context.

### ISSUE THREAD

**Issue by NiniChibi** [yonggekkk/warp-yg#64]
Error: Operation not authorized in this context.

Could not copy 'IP: 端口", It showed error: Operation not authorized in this context.

**Comment by yonggekkk** [comment]
Is there a problem with the Vps?

**Comment by mangoxl99** [comment]
![error](https://github.com/yonggekkk/warp-yg/assets/70678629/d9065157-8a1e-4094-a480-2ab414c23e2d)

**Comment by yonggekkk** [comment]
> ![error](https://private-user-images.githubusercontent.com/70678629/294796656-d9065157-8a1e-4094-a480-2ab414c23e2d.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2Nzc1NjAsIm5iZiI6MTcwNDY3NzI2MCwicGF0aCI6Ii83MDY3ODYyOS8yOTQ3OTY2NTYtZDkwNjUxNTctOGExZS00MDk0LWE0ODAtMmFiNDE0YzIzZTJkLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDAxMjc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0MDk4M2M2ZmZlZjVmZDE5YWE0ZGY3MjBjZWFiNWUyMDhlYzIxOThhMTczYTVhZGUxY2NmMGY4MDU0OWU4ZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8RIXMGCmNGelFzONf2KN-_kenPomJCGn3IFzxmgkQD4)

Try to update your WARP client
