### ISSUE TITLE
warp的ip获取失败

### ISSUE THREAD

**Issue by stark81** [yonggekkk/warp-yg#66]
执行脚本后，跟着视频操作，到这里出现了“warp的IP获取失败”的错误，请问这大概是怎么回事呢？

![image](https://github.com/yonggekkk/warp-yg/assets/48707376/95d7c1b8-6b2c-4676-9dbf-1211b7f56be9)

**Comment by yonggekkk** [comment]
试试使用WARP-GO

**Comment by stark81** [comment]
你的来信已经收到，我将会尽快给你回复。

**Comment by stark81** [comment]
两种方式都试过了，一样的报错咧。然后还有单ipv4、单ipv6以及两者都选的也试了一下，都是同样的报错。

**Comment by yonggekkk** [comment]
> 两种方式都试过了，一样的报错咧。然后还有单ipv4、单ipv6以及两者都选的也试了一下，都是同样的报错。

什么VPS？

**Comment by stark81** [comment]
> 什么VPS？

hosteons的openvz 7 ssd vps，不是很懂
![image](https://github.com/yonggekkk/warp-yg/assets/48707376/96572299-2076-4a12-b103-1ece0d9f7ca4)

**Comment by yonggekkk** [comment]
> > 什么VPS？
> 
> hosteons的openvz 7 ssd vps，不是很懂 ![image](https://user-images.githubusercontent.com/48707376/263514103-96572299-2076-4a12-b103-1ece0d9f7ca4.png)

有提示TUN开启成功吗

**Comment by stark81** [comment]
> 有提示TUN开启成功吗

我记得第一次运行的时候显示开启失败了，然后我又重新执行了脚本就进入脚本的界面了。
但是我邮件询问了vps厂家那边，告知我已经启用了Tun/Tap了。
请问要如何处理呢？

![image](https://github.com/yonggekkk/warp-yg/assets/48707376/aa64af81-387d-4dcb-8009-da4304f85831)

**Comment by yonggekkk** [comment]
> > 有提示TUN开启成功吗
> 
> 我记得第一次运行的时候显示开启失败了，然后我又重新执行了脚本就进入脚本的界面了。 但是我邮件询问了vps厂家那边，告知我已经启用了Tun/Tap了。 请问要如何处理呢？
> 
> ![image](https://user-images.githubusercontent.com/48707376/263515422-aa64af81-387d-4dcb-8009-da4304f85831.png)

 重启下VPS，再执行

**Comment by stark81** [comment]
> 重启下VPS，再执行

现在可以获取IP了，但两个IP都无法访问ChatGPT

![image](https://github.com/yonggekkk/warp-yg/assets/48707376/7fcfcdf5-568f-4f04-b2ee-1bf2917055f5)

**Comment by stark81** [comment]
> 现在可以获取IP了，但两个IP都无法访问ChatGPT

但实测是可以访问ChatGPT的。。。谢谢
