### ISSUE TITLE
cant delete

### ISSUE THREAD

**Issue by shahrokh451** [yonggekkk/warp-yg#68]
please help me to delete this script

**Comment by yonggekkk** [comment]
Choose 4, then choose 3

**Comment by shahrokh451** [comment]
kill script wont work and stop script , stops for a few mint then run again

**Comment by shahrokh451** [comment]
main script wont

**Comment by shahrokh451** [comment]
how do i choose 4 ? when i run the first script again it wont show me the option to choose.it shows me you are behind cloudflare ip

**Comment by shahrokh451** [comment]
thank you
