### ISSUE TITLE
port is closed

### ISSUE THREAD

**Issue by Hasan-Torabi** [yonggekkk/warp-yg#69]
Hi, I got this error. How can I fix it?

 方案二：当前 Socks5-WARP 官方客户端本地代理情况如下
 Socks5 WARP状态：已安装Socks5-WARP客户端，但端口处于关闭状态

Translatipn:
Option 2: The current Socks5-WARP official client local agent situation is as follows
Socks5 WARP status: Socks5-WARP client is installed, but the port is closed

**Comment by yonggekkk** [comment]
Try to use the latest version of vps linux

**Comment by Hasan-Torabi** [comment]
I use latest version of Debian. Which port should be opened?

**Comment by yonggekkk** [comment]
> I use latest version of Debian. Which port should be opened? Thanks


It seems that the debain system has a key replacement problem. It is recommended to use ubuntu22.04.

**Comment by chawaa** [comment]
同样的问题：
![image](https://github.com/yonggekkk/warp-yg/assets/59247295/6c3b6251-386a-498f-9ffa-f2142b539a6b)

**Comment by yuebai01** [comment]
我也是这个问题，之前可以，有次卸载后重新安装就不行了

**Comment by yuebai01** [comment]
系统是乌班图22.0.4，不过已经没事了，完全卸载后重新安装又可以了
