### ISSUE TITLE
大大，为什么我现在只能获取中国IP？能否指定IP？

### ISSUE THREAD

**Issue by MichaelMiao1018** [yonggekkk/warp-yg#75]
方案一：当前 IPV4 接管VPS出站情况如下（WARP监测关闭中）
 WARP状态：运行中，WARP普通账户(无限WARP流量)
 服务商 Cloudflare 获取IPV4地址：104.28.213.202  中国
 奈飞NF解锁情况：死心吧，Netflix不服务当前IP地区
 ChatGPT解锁情况：遗憾，当前IP无法访问ChatGPT官网服务
------------------------------------------------------------------------------------
 方案一：当前 IPV6 接管VPS出站情况如下（WARP监测关闭中）
 WARP状态：运行中，WARP普通账户(无限WARP流量)
 服务商 Cloudflare 获取IPV6地址：2a09:bac5:21b2:28::4:30a  中華人民共和國
 奈飞NF解锁情况：死心吧，Netflix不服务当前IP地区
 ChatGPT解锁情况：遗憾，当前IP无法访问ChatGPT官网服务
------------------------------------------------------------------------------------
方案二：当前 Socks5-WARP 官方客户端本地代理情况如下
 Socks5 WARP状态：运行中，WARP普通账户(无限WARP流量)
 Socks5 端口：40000
 服务商 Cloudflare 获取IPV4地址：104.28.213.199  中国
 奈飞NF解锁情况：死心吧，Netflix不服务当前IP地区
 ChatGPT解锁情况：遗憾，当前IP无法访问ChatGPT官网服务

**Comment by yonggekkk** [comment]
你VPS的IP被CF定为中国区的。无解。。。。可能这VPS的IP是中国IP的广播IP吧

**Comment by MichaelMiao1018** [comment]
我之前都是美区的IP呀，就昨天还是前天开始不行的

**Comment by MichaelMiao1018** [comment]
> 你VPS的IP被CF定为中国区的。无解。。。。可能这VPS的IP是中国IP的广播IP吧

之前用的一点问题没有，然后就昨天还是前天不行的，也无解嘛？VPS的IP是在圣何塞的机房

**Comment by yonggekkk** [comment]
过会再试试吧
