### ISSUE TITLE
Warning: The "clear-custom-endpoint" command will be deprecated in a future release. Please use "tunnel endpoint reset" instead

### ISSUE THREAD

**Issue by 775589898** [yonggekkk/warp-yg#77]
报错是什么原因呀

测试结果已经写入result.csv
Success
Warning: The "clear-custom-endpoint" command will be deprecated in a future release. Please use "tunnel endpoint reset" instead

Success
Warning: The "set-custom-endpoint" command will be deprecated in a future release. Please use "tunnel endpoint set" instead

Success
Success
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
::                                                                 ::
           自选服务器已经设置为162.159.192.139:859
                    丢包率 0.00% 平均延迟 18 ms
::                                                                 ::
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

**Comment by yonggekkk** [comment]
> 报错是什么原因呀
> 
> 测试结果已经写入result.csv Success Warning: The "clear-custom-endpoint" command will be deprecated in a future release. Please use "tunnel endpoint reset" instead
> 
> Success Warning: The "set-custom-endpoint" command will be deprecated in a future release. Please use "tunnel endpoint set" instead
> 
> Success Success ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: :: :: 自选服务器已经设置为162.159.192.139:859 丢包率 0.00% 平均延迟 18 ms :: :: :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

哪个脚本提示的？

**Comment by 775589898** [comment]
配置ip的两个脚本都显示，但是我按照他的意思将clear-custom-endpoint替换成tunnel endpoint reset set-custom-endpoint替换tunnel endpoint set就成功了。我的是win11不知道是不是这个问题

**Comment by 775589898** [comment]
> > 报错是什么原因呀
> > 测试结果已经写入result.csv Success Warning: The "clear-custom-endpoint" command will be deprecated in a future release. Please use "tunnel endpoint reset" instead
> > Success Warning: The "set-custom-endpoint" command will be deprecated in a future release. Please use "tunnel endpoint set" instead
> > Success Success ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: :: :: 自选服务器已经设置为162.159.192.139:859 丢包率 0.00% 平均延迟 18 ms :: :: :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
> 
> 哪个脚本提示的？

请问一下大佬，如果配置成功了ip是不是会变呀

**Comment by yonggekkk** [comment]
> 配置ip的两个脚本都显示，但是我按照他的意思将clear-custom-endpoint替换成tunnel endpoint reset set-custom-endpoint替换tunnel endpoint set就成功了。我的是win11不知道是不是这个问题

不清楚你怎么搞的。。

**Comment by yonggekkk** [comment]
> > > 报错是什么原因呀
> > > 测试结果已经写入result.csv Success Warning: The "clear-custom-endpoint" command will be deprecated in a future release. Please use "tunnel endpoint reset" instead
> > > Success Warning: The "set-custom-endpoint" command will be deprecated in a future release. Please use "tunnel endpoint set" instead
> > > Success Success ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: :: :: 自选服务器已经设置为162.159.192.139:859 丢包率 0.00% 平均延迟 18 ms :: :: :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
> > 
> > 
> > 哪个脚本提示的？
> 
> 请问一下大佬，如果配置成功了ip是不是会变呀

warp对端IP主要是帮助连接用的。。

**Comment by 775589898** [comment]
> > 配置ip的两个脚本都显示，但是我按照他的意思将clear-custom-endpoint替换成tunnel endpoint reset set-custom-endpoint替换tunnel endpoint set就成功了。我的是win11不知道是不是这个问题
> 
> 不清楚你怎么搞的。。
他报的是Warning警告而不是错误，警告的中文意思是“警告：“clear-custom-endpoint”命令将在将来的发行版中弃用。请改用“隧道端点重置””。

**Comment by 775589898** [comment]
> > > > 报错是什么原因呀
> > > > 测试结果已经写入result.csv Success Warning: The "clear-custom-endpoint" command will be deprecated in a future release. Please use "tunnel endpoint reset" instead
> > > > Success Warning: The "set-custom-endpoint" command will be deprecated in a future release. Please use "tunnel endpoint set" instead
> > > > Success Success ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: :: :: 自选服务器已经设置为162.159.192.139:859 丢包率 0.00% 平均延迟 18 ms :: :: :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
> > > 
> > > 
> > > 哪个脚本提示的？
> > 
> > 
> > 请问一下大佬，如果配置成功了ip是不是会变呀
> 
> warp对端IP主要是帮助连接用的。。

所以怎么看有没有配置成功呢？

**Comment by yonggekkk** [comment]
教程有说，修改后连接成功就说明配置成功了

**Comment by 775589898** [comment]
> 教程有说，修改后连接成功就说明配置成功了

okok那没问题了谢谢啦

**Comment by freedomzyb1122** [comment]
甬哥。我实在进行ip优选后设置ip后提示的警告
Warning: The "clear-custom-endpoint" command will be deprecated in a future release. Please use "tunnel endpoint reset" instead

Error: Operation not authorized in this context.
Warning: The "set-custom-endpoint" command will be deprecated in a future release. Please use "tunnel endpoint set" instead

Error: Operation not authorized in this context.
然后warp速度很卡，以前没有这种情况。

**Comment by yonggekkk** [comment]
> 甬哥。我实在进行ip优选后设置ip后提示的警告 Warning: The "clear-custom-endpoint" command will be deprecated in a future release. Please use "tunnel endpoint reset" instead
> 
> Error: Operation not authorized in this context. Warning: The "set-custom-endpoint" command will be deprecated in a future release. Please use "tunnel endpoint set" instead
> 
> Error: Operation not authorized in this context. 然后warp速度很卡，以前没有这种情况。

warp客户端与优选工具都下载最新
