### ISSUE TITLE
大佬求助

### ISSUE THREAD

**Issue by SkyFutu** [yonggekkk/warp-yg#8]
我是搬瓦工的vps，用了大佬的脚本，但是用完后v2ray和ssr都Ping不同了，并且对应的ip也变成cf的了，这样v2ray就用不了了，我ssr的ip也改了但是可以连（连vps的ip而不是cf的）不过这样就访问不了chatgpt了咋搞

**Comment by yonggekkk** [comment]
不要改客户端任何参数！

**Comment by SkyFutu** [comment]
![QQ图片20230401095723](https://user-images.githubusercontent.com/119418823/229260536-e7c5c18d-5a10-4591-889c-2d818a7be542.png)
![QQ图片20230401095844](https://user-images.githubusercontent.com/119418823/229260542-66f53e65-5a59-4e8c-8a7c-6682161daf0f.png)
大佬你看看，还是说我装proxy的脚本有问题

**Comment by yonggekkk** [comment]
KCP的没试过，你试下WS或者TCP看看

**Comment by SkyFutu** [comment]
> KCP的没试过，你试下WS或者TCP看看

感谢，可以了，但是我注册chatgpt的时候无法注册，显示‘Too many signups from the same IP’

**Comment by yonggekkk** [comment]
> > KCP的没试过，你试下WS或者TCP看看
> 
> 感谢，可以了，但是我注册chatgpt的时候无法注册，显示‘Too many signups from the same IP’

用warp的IPV6注册。。warp的IPV4重复率太高，必定被滥用，尤其是美区的

**Comment by SkyFutu** [comment]
> > > KCP的没试过，你试下WS或者TCP看看
> > 
> > 
> > 感谢，可以了，但是我注册chatgpt的时候无法注册，显示‘Too many signups from the same IP’
> 
> 用warp的IPV6注册。。warp的IPV4重复率太高，必定被滥用，尤其是美区的

那大佬我这台机器可以迁移地区，是不是迁移到其他地区（如波兰等就）是不是就有可能解决？这台vps没ipv6难受

**Comment by yonggekkk** [comment]
WARP能给你IPV6地址呀！可以做好分流即可！当然你换到别的地区用WARP的IPV4也可以，随你啦

**Comment by SkyFutu** [comment]
> 

![QQ图片20230401154836](https://user-images.githubusercontent.com/119418823/229273163-4e574712-3d25-4dae-890b-f48c15e4cdd9.png)

**Comment by SkyFutu** [comment]
> > 
> 
> ![QQ图片20230401154836](https://user-images.githubusercontent.com/119418823/229273163-4e574712-3d25-4dae-890b-f48c15e4cdd9.png)

我再试试吧
