### ISSUE TITLE
WARP-go, 好像和Nginx Proxy Manager反代冲突,如何解决?

### ISSUE THREAD

**Issue by tiancool** [yonggekkk/warp-yg#80]
安装WARP-go后有新的出站IP,但这样会导致Nginx Proxy Manager反代无法使用,博主有没有办法解决

**Comment by yonggekkk** [comment]
目前脚本提供的方案一是全局接管出站，相当于把本地IP给变了。。。。或许你用socks5的WARP吧

**Comment by tiancool** [comment]
Socks5-WARP 不支持 arm64，请问博主这个怎么解决，想给openai 分流，不想全局接管呢

**Comment by tiancool** [comment]
我安装了ing-box，但所有相关命令，都是要安装WARP才能设置分流呀，能简单说下步骤吗，感谢

**Comment by yonggekkk** [comment]
> 我安装了sing-box，但所有相关命令，都是要安装WARP才能设置分流呀，能简单说下步骤吗，感谢

https://youtu.be/QwTapeVPeB0
