### ISSUE TITLE
warp 优选ip在大陆很多国外的网站打不开能提示一下吗？

### ISSUE THREAD

**Issue by zhuchaojiebao** [yonggekkk/warp-yg#82]
用一段优选ip后，发现一些国外的网站无法打开。很苦恼这个问题。无法解决。

**Comment by yonggekkk** [comment]
什么网站可以？什么网站不可以？

**Comment by zhuchaojiebao** [comment]
> 什么网站可以？什么网站不可以？

大部分网站可以，像领英这个网站就一直打不开！

**Comment by yonggekkk** [comment]
> > 什么网站可以？什么网站不可以？
> 
> 大部分网站可以，像领英这个网站就一直打不开！

用VPS。。。本地WARP客户端识别的还是中国

**Comment by zhuchaojiebao** [comment]
> > > 什么网站可以？什么网站不可以？
> > 
> > 大部分网站可以，像领英这个网站就一直打不开！
> 
> 用VPS。。。本地WARP客户端识别的还是中国

- 谢谢！对这方面的技术不了解，网上看到的也是一知半解的！

**Comment by yonggekkk** [comment]
> > > > 什么网站可以？什么网站不可以？
> > > 
> > > 
> > > 大部分网站可以，像领英这个网站就一直打不开！
> > 
> > 
> > 用VPS。。。本地WARP客户端识别的还是中国
> 
> * 谢谢！对这方面的技术不了解，网上看到的也是一知半解的！

有问题随时可以问。虽然本地识别为中国，但也可以上绝大部分不限制中国IP的外网。。
