### ISSUE TITLE
甬哥求救啊！

### ISSUE THREAD

**Issue by zhuchaojiebao** [yonggekkk/warp-yg#83]
路由器刷了老毛子固件，使用AP-Client+AP 无线桥接模式后，内网的DHCP.也开启了。但就是没有网络。应该怎么设置啊！![Screenshot_2023-12-16-16-05-18-048_com.android.browser-edit.jpg](https://github.com/yonggekkk/warp-yg/assets/51844021/f03647b8-a2d2-4604-8467-0717037329b0)

![Screenshot_2023-12-16-16-05-37-853_com.android.browser-edit.jpg](https://github.com/yonggekkk/warp-yg/assets/51844021/880dac9c-77a7-4bd2-9acd-619fce31020b)

![Screenshot_2023-12-16-16-04-55-037_com.android.settings-edit.jpg](https://github.com/yonggekkk/warp-yg/assets/51844021/9e957aad-8a4b-45bd-b7fb-0c16ba6db574)

**Comment by yonggekkk** [comment]
.....这与WARP有什么关系？

**Comment by zhuchaojiebao** [comment]
这不是没有找到会的人么

**Comment by yonggekkk** [comment]
～  ～！

**Comment by 1728643928** [comment]
你都桥接了，还开dhcp干嘛
