### ISSUE TITLE
【讨论】方案一总是失败，方案二确能轻松获得IP

### ISSUE THREAD

**Issue by avtsavts2021** [yonggekkk/warp-yg#86]
```bash
共执行10次，第1次获取warp的IP中……
遗憾！warp的IP获取失败
共执行10次，第2次获取warp的IP中……
遗憾！warp的IP获取失败
共执行10次，第3次获取warp的IP中……
遗憾！warp的IP获取失败
共执行10次，第4次获取warp的IP中……
遗憾！warp的IP获取失败
共执行10次，第5次获取warp的IP中……
遗憾！warp的IP获取失败
共执行10次，第6次获取warp的IP中……
遗憾！warp的IP获取失败
共执行10次，第7次获取warp的IP中……
遗憾！warp的IP获取失败
共执行10次，第8次获取warp的IP中……
遗憾！warp的IP获取失败
共执行10次，第9次获取warp的IP中……
遗憾！warp的IP获取失败
共执行10次，第10次获取warp的IP中……
遗憾！warp的IP获取失败
安装WARP失败，还原VPS，卸载WARP

提示：
你或许可以使用方案二或方案三来实现WARP
也可以选择WGCF核心来安装WARP方案一
```
这是什么原因呢？

**Comment by yonggekkk** [comment]
换WGCF核心来安装

**Comment by avtsavts2021** [comment]
摸索了一下，换WGCF核心问题依然存在。

不过我运气很好，尝试手动更换了主机的DNS配置，就可以成功获取IP了

**Comment by yonggekkk** [comment]
> 摸索了一下，换WGCF核心问题依然存在。
> 
> 不过我运气很好，尝试手动更换了主机的DNS配置，就可以成功获取IP了

改为什么了？

**Comment by avtsavts2021** [comment]
> > > > 摸索了一下，换WGCF核心问题依然存在。
> > > > 不过我运气很好，尝试手动更换了主机的DNS配置，就可以成功获取IP了
> > > 
> > > 
> > > 改为什么了？
> > 
> > 
> > IPv4:
> > ```shell
> > 1.1.1.1
> > 1.0.0.1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > IPv6:
> > ```shell
> > 2606:4700:4700::1111
> > 2606:4700:4700::1001
> > ```
> 
> 原来是谷歌的，换回CF的就可以了？

貌似是这样

**Comment by yonggekkk** [comment]
> > > > > 摸索了一下，换WGCF核心问题依然存在。
> > > > > 不过我运气很好，尝试手动更换了主机的DNS配置，就可以成功获取IP了
> > > > 
> > > > 
> > > > 改为什么了？
> > > 
> > > 
> > > IPv4:
> > > ```shell
> > > 1.1.1.1
> > > 1.0.0.1
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > IPv6:
> > > ```shell
> > > 2606:4700:4700::1111
> > > 2606:4700:4700::1001
> > > ```
> > 
> > 
> > 原来是谷歌的，换回CF的就可以了？
> 
> 貌似是这样

Ok
