### ISSUE TITLE
IPV4和IPV6均不存在

### ISSUE THREAD

**Issue by NincoAX** [yonggekkk/warp-yg#93]
VPS系统信息如下：
 操作系统: Ubuntu 22.04.4 LTS  内核版本: 5.15.0  CPU架构 : amd64  虚拟化类型: vmware
------------------------------------------------------------------------------------
 方案一：当前 IPV4 接管VPS出站情况如下（WARP监测已开启）
 IPV4状态：不存在IPV4地址 
------------------------------------------------------------------------------------
 方案一：当前 IPV6 接管VPS出站情况如下（WARP监测已开启）
 IPV6状态：不存在IPV6地址 
------------------------------------------------------------------------------------
IPV4与IPV6都为不存在，建议如下：
1、原来安装wgcf的，选择9切换到warp-go重装warp
2、原来安装warp-go的，选择10切换到wgcf重装warp
切记：如依旧如此，建议卸载并重启VPS，再重装方案一

路由器拨号获得公网IP（v4和v6），下接虚拟机安装了ubuntu，网关指向路由器，并映射了80端口，但获取不到IP，提示上述信息；方案二的socks5正常。

以前成功获取过1次，但是后来重装了系统就获取不到IP了，不知道问题出在哪里，还有办法解决吗？

**Comment by yonggekkk** [comment]
WGCF与WARP-GO都试下

**Comment by NincoAX** [comment]
> WGCF与WARP-GO都试下

2个都试了，也是不行，尝试重新安装也没生效

**Comment by yonggekkk** [comment]
脚本不支持路由器
