### ISSUE TITLE
出站规则

### ISSUE THREAD

**Issue by 1728643928** [yonggekkk/warp-yg#94]
比如我vps无法访问国内的某一个网址，开warp就可以访问了，但是他是全局的，导致我所有出站流量都走了warp
希望能指定域名走warp，别的都不走，不是x-ui的分流，x-ui我看了视频试了，不行，我并不是在vps上搭了节点，而是搭了一个机器人，访问国内某一个网站，访问不了，是这个意思

**Comment by yonggekkk** [comment]
一个机器人？代理脚本装不上吧

**Comment by 1728643928** [comment]
就是QQ机器人，一些指令，比如说查询游戏里的装备，他会向游戏服务器发送请求，但是连接超时，开了warp之后才能正常访问

**Comment by 1728643928** [comment]
> 一个机器人？代理脚本装不上吧

就是QQ机器人，一些指令，比如说查询游戏里的装备，他会向游戏服务器发送请求，但是连接超时，开了warp之后才能正常访问
